<div style="border:solid Chocolate 2px; padding: 40px">

<b>Антон, привет!</b>

Меня зовут Евгений Головин, я буду ревьюером твоего проекта. Если ты не против, то предлагаю построить наше общение на "ты" ;) Если удобнее на "вы", то нет проблем, только скажи об этом. 

В ходе работы я оставил тебе комментарии <font color='green'>зеленого</font>, <font color='gold'>желтого</font> и <font color='red'>красного</font> цветов. Сейчас объясню, что они значат:

<br/>

<div class="alert alert-success">
<h2> Комментарий ревьюера <a class="tocSkip"> </h2>

<b>Все супер!👍:</b> Решение на этом шаге является полностью правильным.
</div>

<br/>

<div class="alert alert-warning">
    <h2> Комментарий ревьюера <a class="tocSkip"> </h2>
    
<b>Небольшие замечания и рекомендации💡:</b> Решение на этом шаге станет еще лучше, если внести небольшие коррективы.
</div>


<br/>
<div class="alert alert-block alert-danger">
<h2> Комментарий ревьюера <a class="tocSkip"></h2>

    
<b>На доработку🤔:</b>
 Решение на этом шаге требует существенной переработки и внесения правок. Напоминаю, что проект не может быть принят с первого раза, если ревью содержит комментарии, рекомендующие доработать шаги.
</div>
    
Увидев мой комментарий, не удаляй его, он будет очень полезен в случае повторной проверки работы :)
    
<div class="alert alert-info">
<b>А свой помечай вот так, чтобы я его не потерял ;)</b> 
</div>
    
На мои комменатрии можно и нужно реагировать, только делать это стоит так, чтобы твои и мои комменты не смешались: выделяй свои цветами, сильно отличающимися от моих.
    
Увидев у тебя неточность, в первый раз я лишь укажу на ее наличие и дам тебе возможность самому найти и исправить ее. На реальной работе твой руководитель будет поступать также, и я пытаюсь подготовить тебя именно к работе аналитиком. Но если ты пока не справишься с такой задачей - при следующей проверке я дам более точную подсказку!

# Исследование данных о российском кинопрокате

Заказчик этого исследования — Министерство культуры Российской Федерации. 

В данном проекте я постараюсь изучить рынок российского кинопроката и выявить текущие тренды, уделю внимание фильмам получившим государственную поддержку, а также попробую ответить на вопрос, насколько такие фильмы интересны зрителю.

Данные, с которыми я буду работать, опубликованы на [портале открытых данных Министерства культуры](http://opendata.mkrf.ru/). Набор данных содержит информацию о прокатных удостоверениях, сборах и государственной поддержке фильмов, а также информацию с сайта КиноПоиск.

# План работы
1. Осмотр данных
2. Предобработка данных
3. Исследовательский анализ данных
4. Исследование фильмов с гос поддержкой
5. Общий вывод

<div class="alert alert-warning">
    <h2> Комментарий ревьюера v1 <a class="tocSkip"> </h2>
    
<b>Небольшие замечания и рекомендации💡:</b>  Цель работы можно сформулировать более емко и кратко, план работы есть, не хватает только описания данных

### Шаг 1. Откройте файлы с данными и объедините их в один датафрейм. 

Объедините данные таким образом, чтобы все объекты из датасета `mkrf_movies` обязательно вошли в получившийся датафрейм. 

<div id="accordion">
    <div class="card">
        <div class="card-header" id="headingThree">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseHint_0" aria-expanded="false" aria-controls="collapseHint_0">Подсказка</button>
        </div>
        <div id="collapseHint_0" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
            <div class="card-body">
Обратите внимание на тип данных столбца, по которому будете соединять датафреймы. Тип данных этих столбцов должен быть одинаковым в обоих датафреймах.
            </div>
        </div>
    </div>
</div>

Сначала импортируем необходимые библиотеки

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

Считаем данные из обоих датасетов

In [3]:
mkrf_shows = pd.read_csv("/datasets/mkrf_shows.csv")
mkrf_movies = pd.read_csv("/datasets/mkrf_movies.csv")

<div class="alert alert-block alert-danger">
<h2> Комментарий ревьюера v1<a class="tocSkip"></h2>

<b>На доработку🤔:</b>  Прежде всего важно посмотреть на данные - правильно ли они прочитались. Выведи несколько строк, пожалуйста

Взглянем на общую информацию о данных, она нам сможет подсказать как их объединить

In [4]:
mkrf_shows.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3158 entries, 0 to 3157
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   puNumber    3158 non-null   int64
 1   box_office  3158 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 49.5 KB

In [5]:
mkrf_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7486 entries, 0 to 7485
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   title                  7486 non-null   object
 1   puNumber               7486 non-null   object
 2   show_start_date        7486 non-null   object
 3   type                   7486 non-null   object
 4   film_studio            7468 non-null   object
 5   production_country     7484 non-null   object
 6   director               7477 non-null   object
 7   producer               6918 non-null   object
 8   age_restriction        7486 non-null   object
 9   refundable_support     332 non-null    float64
 10  nonrefundable_support  332 non-null    float64
 11  budget                 332 non-null    float64
 12  financing_source       332 non-null    object
 13  ratings                6519 non-null   object
 14  genres                 6510 non-null   object
dtypes: float64(3), object(12)
memory usage: 877.4+ KB

Видно что колонка `puNumber` присутствует в обоих датасетах, ее то мы и используем для объединения данных. Только есть одна проблема - типы данных в колонках различаются. Попробуем привести их к одному типу. Используем метод `to_numeric` и все невалидные значения превратим в `NaN` с помощью параметра `errors`

In [6]:
mkrf_movies['puNumber'] = pd.to_numeric(mkrf_movies['puNumber'], errors='coerce').astype('Int64')

<div class="alert alert-success">
<h2> Комментарий ревьюера v1 <a class="tocSkip"> </h2>

<b>Все супер!👍:</b> Верное решение! Здорово, что именно так решил - приводиь к числу, а не наоборот, приводить в другом датафрейме к строке

После изменения типа данных удалим все `NaN` значения

In [7]:
mkrf_movies = mkrf_movies.dropna(subset=['puNumber'])

Для объединения я использую метод `pandas` под названием `merge`. Так как я хочу, чтобы все объекты из датасета `mkrf_movies` обязательно вошли в получившийся датафрейм, то я использую параметр `how` со значением `left`

In [8]:
data = pd.merge(mkrf_movies, mkrf_shows, on='puNumber', how="left")
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7485 entries, 0 to 7484
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   title                  7485 non-null   object
 1   puNumber               7485 non-null   Int64
 2   show_start_date        7485 non-null   object
 3   type                   7485 non-null   object
 4   film_studio            7467 non-null   object
 5   production_country     7483 non-null   object
 6   director               7476 non-null   object
 7   producer               6917 non-null   object
 8   age_restriction        7485 non-null   object
 9   refundable_support     332 non-null    float64
 10  nonrefundable_support  332 non-null    float64
 11  budget                 332 non-null    float64
 12  financing_source       332 non-null    object
 13  ratings                6519 non-null   object
 14  genres                 6510 non-null   object
 15  box_office             3158 non-null   float64
dtypes: Int64(1), float64(4), object(11)
memory usage: 1001.4+ KB

<div class="alert alert-block alert-danger">
<h2> Комментарий ревьюера v1<a class="tocSkip"></h2>

<b>На доработку🤔:</b>   Сделай, пожалуйста, вывод по ттому, насколько правильно объединились данные

### Шаг 2. Предобработка данных

#### Шаг 2.1. Проверка типов данных

Взглянем на другие типы данных в датасете и преобразуем их там, где это необходимо.

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7485 entries, 0 to 7484
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   title                  7485 non-null   object
 1   puNumber               7485 non-null   Int64
 2   show_start_date        7485 non-null   object
 3   type                   7485 non-null   object
 4   film_studio            7467 non-null   object
 5   production_country     7483 non-null   object
 6   director               7476 non-null   object
 7   producer               6917 non-null   object
 8   age_restriction        7485 non-null   object
 9   refundable_support     332 non-null    float64
 10  nonrefundable_support  332 non-null    float64
 11  budget                 332 non-null    float64
 12  financing_source       332 non-null    object
 13  ratings                6519 non-null   object
 14  genres                 6510 non-null   object
 15  box_office             3158 non-null   float64
dtypes: Int64(1), float64(4), object(11)
memory usage: 1001.4+ KB

In [10]:
data.head()

,title,puNumber,show_start_date,type,film_studio,production_country,director,producer,age_restriction,refundable_support,nonrefundable_support,budget,financing_source,ratings,genres,box_office
0,Открытый простор,221048915,2015-11-27T12:00:00.000Z,Художественный,"Тачстоун Пикчерз, Кобальт Пикчерз, Бикон Пикче...",США,Кевин Костнер,"Дэвид Валдес, Кевин Костнер, Джейк Эбертс",«18+» - запрещено для детей,NaN,NaN,NaN,NaN,7.2,"боевик,драма,мелодрама",NaN
1,Особо важное задание,111013716,2016-09-13T12:00:00.000Z,Художественный,"Киностудия ""Мосфильм""",СССР,Е.Матвеев,NaN,«6+» - для детей старше 6 лет,NaN,NaN,NaN,NaN,6.6,"драма,военный",NaN
2,Особо опасен,221038416,2016-10-10T12:00:00.000Z,Художественный,"Юниверсал Пикчерз, Кикстарт Продакшнз, Марк Пл...",США,Тимур Бекмамбетов,"Джим Лемли, Джейсон Нетер, Марк Е.Платт, Яйн Смит",«18+» - запрещено для детей,NaN,NaN,NaN,NaN,6.8,"фантастика,боевик,триллер",NaN
3,Особо опасен,221026916,2016-06-10T12:00:00.000Z,Художественный,"Юниверсал Пикчерз, Кикстарт Продакшнз, Марк Пл...",США,Тимур Бекмамбетов,"Джим Лемли, Джейсон Нетер, Марк Е.Платт, Яйн Смит",«18+» - запрещено для детей,NaN,NaN,NaN,NaN,6.8,"фантастика,боевик,триллер",NaN
4,Особо опасен,221030815,2015-07-29T12:00:00.000Z,Художественный,"Юниверсал Пикчерз, Кикстарт Продакшнз, Марк Пл...",США,Тимур Бекмамбетов,"Джим Лемли, Джейсон Нетер, Марк Е.Платт, Яйн Смит",«18+» - запрещено для детей,NaN,NaN,NaN,NaN,6.8,"фантастика,боевик,триллер",NaN

Исходя и этих данных можно преобразовать следующие столбцы:
- `title` можно превратить в тип `string`
- `type` можно превратить в тип `string`
- `production country` можно превратить в тип `string`
- `director` можно превратить в тип `string`
- `ratings` можно превратить в тип `float`

#### Шаг 2.2. Изучите пропуски в датафрейме

- Объясните, почему заполнили пропуски определённым образом или почему не стали этого делать.

In [11]:
data['title'] = data['title'].astype('string')
data['type'] = data['type'].astype('string')
data['production_country'] = data['production_country'].astype('string')
data['director'] = data['director'].astype('string')
data['genres'] = data['genres'].astype('string')

In [12]:
data['ratings'].unique()

array(['7.2', '6.6', '6.8', '7.7', '8.3', '8.0', '7.8', '8.1', '7.1',
       '6.0', '7.4', '5.8', '8.7', '6.3', '6.9', '5.0', '4.3', '7.3',
       '7.0', '6.4', nan, '8.2', '7.5', '6.7', '7.9', '5.9', '6.2', '5.6',
       '6.5', '2.4', '7.6', '6.1', '8.6', '8.5', '8.8', '5.5', '5.1',
       '5.7', '5.4', '99%', '4.4', '4.5', '5.3', '4.1', '8.4', '2.6',
       '3.8', '4.6', '4.8', '4.0', '3.0', '1.6', '4.2', '5.2', '4.7',
       '4.9', '3.9', '2.7', '3.3', '2.9', '28%', '3.7', '1.4', '3.1',
       '97%', '3.5', '3.2', '2.8', '1.5', '2.1', '2.5', '9.2', '3.4',
       '1.1', '3.6', '83%', '64%', '91%', '94%', '62%', '79%', '90%',
       '19%', '88%', '1.0', '89%', '1.3', '1.9', '1.8', '1.2', '1.7',
       '9.0', '98%', '8.9', '9.1'], dtype=object)

Конвертация из типа `object` в тип `float` скорее всего пройдет не так гладко как хотелось бы из-за знака `%`. С помощью метода `apply` я применю кастомную функцию для обработки таких значений

In [13]:
def convert_rating(value):
    if isinstance(value, str) and value.endswith('%'): 
        return float(value.rstrip('%')) / 100
    return value

data['ratings'] = data['ratings'].apply(convert_rating)
data['ratings'] = data['ratings'].astype('float')
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7485 entries, 0 to 7484
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   title                  7485 non-null   string
 1   puNumber               7485 non-null   Int64
 2   show_start_date        7485 non-null   object
 3   type                   7485 non-null   string
 4   film_studio            7467 non-null   object
 5   production_country     7483 non-null   string
 6   director               7476 non-null   string
 7   producer               6917 non-null   object
 8   age_restriction        7485 non-null   object
 9   refundable_support     332 non-null    float64
 10  nonrefundable_support  332 non-null    float64
 11  budget                 332 non-null    float64
 12  financing_source       332 non-null    object
 13  ratings                6519 non-null   float64
 14  genres                 6510 non-null   string
 15  box_office             3158 non-null   float64
dtypes: Int64(1), float64(5), object(5), string(5)
memory usage: 1001.4+ KB

Отлично, теперь все типы правильны

<div class="alert alert-success">
<h2> Комментарий ревьюера v1 <a class="tocSkip"> </h2>

<b>Все супер!👍:</b> Отлично!

#### Шаг 2.3. Изучите дубликаты в датафрейме
- Проверьте, есть ли в данных дубликаты. Опишите причины, которые могли повлиять на появление дублей.

In [14]:
print(data.duplicated().any())

False

Как можно увидеть, дубликатов в данных нет

#### Шаг 2.4. Изучите категориальные значения

- Посмотрите, какая общая проблема встречается почти во всех категориальных столбцах;
- Исправьте проблемные значения в поле `type`.

<div id="accordion">
    <div class="card">
        <div class="card-header" id="headingThree">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseHint_1" aria-expanded="false" aria-controls="collapseHint_1">Подсказка</button>
        </div>
        <div id="collapseHint_1" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
            <div class="card-body">
В поле <code>type</code> есть несколько значений, у которых появился пробел в начале строки. Самый простой способ их «починить» -- использовать метод <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.str.strip.html#pandas.Series.str.strip">.str.strip</a>. Этот метод удаляет все пробелы, которые встречаются в начале и в конце строки. Применяют его таким образом:<br>
<code>df['type'].str.strip()</code>
            </div>
        </div>
    </div>
</div>

In [15]:
data['type'].unique()

<StringArray>
[            'Художественный',               'Анимационный',
                     'Прочие',             'Документальный',
          'Научно-популярный',            ' Художественный',
              ' Анимационный', 'Музыкально-развлекательный']
Length: 8, dtype: string

Можно заметить, что в колонке type присутствуют неявные дубликаты из-за наличия лишнего пробела

In [16]:
data['type'] = data['type'].str.strip()
data['type'].unique()

<StringArray>
[            'Художественный',               'Анимационный',
                     'Прочие',             'Документальный',
          'Научно-популярный', 'Музыкально-развлекательный']
Length: 6, dtype: string

Теперь все отлично

<div class="alert alert-block alert-danger">
<h2> Комментарий ревьюера v1<a class="tocSkip"></h2>

<b>На доработку🤔:</b>  Также нужно проверить и другие категориальные столбцы, их много

#### Шаг 2.5. Проверьте количественные значения

- Проверьте, обнаружились ли в таких столбцах подозрительные данные. Как с такими данными лучше поступить?

<div id="accordion">
    <div class="card">
        <div class="card-header" id="headingThree">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseHint_budget" aria-expanded="false" aria-controls="collapseHint_budget">Подсказка</button>
        </div>
        <div id="collapseHint_budget" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
            <div class="card-body">
Обратите внимание на описание столбца <code>budget</code>. Как этот столбец соотносится с двумя другими: <code>refundable_support</code> и <code>nonrefundable_support</code>?
            </div>
        </div>
    </div>
</div>

Взглянув на датасет, можно понять что столбец бюджета - это сумма возращаемой финансовой помощи и безвозвратной финансовой помощи. Для чистки данных можно применить функцию, чтобы пересчитать все пропущенные значение, где возможно. Т.е. если мы знаем общий бюджет и знаем сумму возращаемой финансовой помощи, мы можем рассчитать 3й столбец

In [17]:
def budget_cleaning(row):
    if sum(pd.notna([row['budget'], row['refundable_support'], row['nonrefundable_support']])) >= 2:
        if pd.isna(row['budget']):
            row['budget'] = row['refundable_support'] + row['nonrefundable_support']
        elif pd.isna(row['refundable_support']):
            row['refundable_support'] = row['budget'] - row['nonrefundable_support']
        elif pd.isna(row['nonrefundable_support']):
            row['nonrefundable_support'] = row['budget'] - row['refundable_support']
    return row

data = data.apply(budget_cleaning, axis=1)

<div class="alert alert-success">
<h2> Комментарий ревьюера v1 <a class="tocSkip"> </h2>

<b>Все супер!👍:</b> Отлично!

#### Шаг 2.6. Добавьте новые столбцы

Создадим отдельный столбец о годе проката

In [18]:
data['year'] = data['show_start_date'].apply(lambda x: x[:4])
data.head()

,title,puNumber,show_start_date,type,film_studio,production_country,director,producer,age_restriction,refundable_support,nonrefundable_support,budget,financing_source,ratings,genres,box_office,year
0,Открытый простор,221048915,2015-11-27T12:00:00.000Z,Художественный,"Тачстоун Пикчерз, Кобальт Пикчерз, Бикон Пикче...",США,Кевин Костнер,"Дэвид Валдес, Кевин Костнер, Джейк Эбертс",«18+» - запрещено для детей,NaN,NaN,NaN,NaN,7.2,"боевик,драма,мелодрама",NaN,2015
1,Особо важное задание,111013716,2016-09-13T12:00:00.000Z,Художественный,"Киностудия ""Мосфильм""",СССР,Е.Матвеев,NaN,«6+» - для детей старше 6 лет,NaN,NaN,NaN,NaN,6.6,"драма,военный",NaN,2016
2,Особо опасен,221038416,2016-10-10T12:00:00.000Z,Художественный,"Юниверсал Пикчерз, Кикстарт Продакшнз, Марк Пл...",США,Тимур Бекмамбетов,"Джим Лемли, Джейсон Нетер, Марк Е.Платт, Яйн Смит",«18+» - запрещено для детей,NaN,NaN,NaN,NaN,6.8,"фантастика,боевик,триллер",NaN,2016
3,Особо опасен,221026916,2016-06-10T12:00:00.000Z,Художественный,"Юниверсал Пикчерз, Кикстарт Продакшнз, Марк Пл...",США,Тимур Бекмамбетов,"Джим Лемли, Джейсон Нетер, Марк Е.Платт, Яйн Смит",«18+» - запрещено для детей,NaN,NaN,NaN,NaN,6.8,"фантастика,боевик,триллер",NaN,2016
4,Особо опасен,221030815,2015-07-29T12:00:00.000Z,Художественный,"Юниверсал Пикчерз, Кикстарт Продакшнз, Марк Пл...",США,Тимур Бекмамбетов,"Джим Лемли, Джейсон Нетер, Марк Е.Платт, Яйн Смит",«18+» - запрещено для детей,NaN,NaN,NaN,NaN,6.8,"фантастика,боевик,триллер",NaN,2015

- Создайте два столбца: с именем и фамилией главного режиссёра и основным жанром фильма. В столбцы войдут первые значения из списка режиссёров и жанров соответственно.

<div id="accordion">
    <div class="card">
        <div class="card-header" id="headingThree">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseHint_2" aria-expanded="false" aria-controls="collapseHint_2">Подсказка</button>
        </div>
        <div id="collapseHint_2" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
            <div class="card-body">
Чтобы создать такие столбцы, лучше всего использовать собственную функцию. Эту функцию можно применить к двум столбцам сразу. 
            </div>
        </div>
    </div>
</div>

In [19]:
data['main_genre'] = data['genres'].apply(lambda x: x.split(',')[0] if pd.notna(x) else None)

Посчитаем, какую долю от общего бюджета фильма составляет государственная поддержка.

In [20]:
def ref_sprt_percentage(row):
    refundable_support = row['refundable_support']
    budget = row['budget']
    
    if not pd.isna(refundable_support) and not pd.isna(budget) and budget != 0:
        row['refundable_support_portion'] = refundable_support / budget
    else:
        row['refundable_support_portion'] = pd.NA 
    
    return row

data = data.apply(ref_sprt_percentage, axis=1)

<div class="alert alert-success">
<h2> Комментарий ревьюера v1 <a class="tocSkip"> </h2>

<b>Все супер!👍:</b> Столбцы добавлены верно!

### Шаг 3. Проведите исследовательский анализ данных

Сгруппируем количество фильмов по годам и общее кол-во фильмов

In [21]:
movies_with_box_office = (
        data.dropna(subset=['box_office'])
          .groupby('year')
          .size()
          .rename("movies_with_box_office")
)
display(movies_with_box_office)

year
2010    105
2011    109
2012    128
2013    184
2014    279
2015    465
2016    526
2017    357
2018    475
2019    530
Name: movies_with_box_office, dtype: int64

In [22]:
movies_per_year = (
    data.groupby('year')
      .size()
      .rename("total_movies")
)
display(movies_per_year)

year
2010    985
2011    622
2012    593
2013    630
2014    806
2015    705
2016    818
2017    505
2018    891
2019    930
Name: total_movies, dtype: int64

Объединим обе таблицы и посчитаем процент фильмов с указанной информацией о прокате в кинотеатрах

In [23]:
yearly_stats = pd.concat([movies_per_year, movies_with_box_office], axis=1).fillna(0)
yearly_stats['box_office_percentage'] = yearly_stats['movies_with_box_office'] / yearly_stats['total_movies']
display(yearly_stats)

      total_movies  movies_with_box_office  box_office_percentage
year
2010           985                     105               0.106599
2011           622                     109               0.175241
2012           593                     128               0.215852
2013           630                     184               0.292063
2014           806                     279               0.346154
2015           705                     465               0.659574
2016           818                     526               0.643032
2017           505                     357               0.706931
2018           891                     475               0.533109
2019           930                     530               0.569892

Заметно что более поздние года (2015-2019) имеют куда большую доли представленной информации с пиков в 2017, где доля составила 70%

<div class="alert alert-warning">
    <h2> Комментарий ревьюера v1 <a class="tocSkip"> </h2>
    
<b>Небольшие замечания и рекомендации💡:</b>  Отлично! Для наглядности предлагаю добавить визуализацию

<div class="alert alert-block alert-danger">
<h2> Комментарий ревьюера v1<a class="tocSkip"></h2>

<b>На доработку🤔:</b>   Также посчитй, пожалуйста, долю фильмов с известными данными о прокате по всему датафрейму

Изучим, как менялась динамика проката по годам.

In [24]:
box_office_by_year = data.groupby('year')['box_office'].sum()

min_year = box_office_by_year.idxmin()
max_year = box_office_by_year.idxmax()

print(f"Год с наименьшими сборами: {min_year}, Сборы: {box_office_by_year[min_year]}")
print(f"Год с наибольшими сборами: {max_year}, Сборы: {box_office_by_year[max_year]}")

Год с наименьшими сборами: 2010, Сборы: 2428654.0
Год с наибольшими сборами: 2018, Сборы: 49668403134.31999

In [25]:
display(box_office_by_year)

year
2010    2.428654e+06
2011    1.410276e+07
2012    6.955423e+06
2013    2.979971e+07
2014    7.444952e+09
2015    3.949737e+10
2016    4.786630e+10
2017    4.856371e+10
2018    4.966840e+10
2019    4.842571e+10
Name: box_office, dtype: float64

Рекордная сумма проката была получена в 2012 году. В последующие года цены выросла примерно в 2 раза, скорее всего это связано с инфляцией и ослаблением рубля

<div class="alert alert-warning">
    <h2> Комментарий ревьюера v1 <a class="tocSkip"> </h2>
    
<b>Небольшие замечания и рекомендации💡:</b>  Таакже можно добваить визуализаацию, чтобы было наглядно

Взглянем на средние и медианные значения по каждому года

In [26]:
pivot_table = data.pivot_table(
    index='year', 
    values='box_office', 
    aggfunc=['mean', 'median']
)

pivot_table.columns = ['avg_box_office', 'median_box_office']
display(pivot_table)

      avg_box_office  median_box_office
year
2010    2.313004e+04           1700.000
2011    1.293832e+05           3000.000
2012    5.433924e+04           5660.000
2013    1.619549e+05           3522.500
2014    2.668442e+07          18160.000
2015    8.494057e+07        4920933.000
2016    9.100057e+07        3846679.410
2017    1.360328e+08        9968340.000
2018    1.045651e+08        8891102.210
2019    9.136926e+07        4627798.345

Влияет ли возрастное ограничение аудитории («6+», «12+», «16+», «18+» и т. д.) на сборы фильма в прокате в период с 2015 по 2019 год? Фильмы с каким возрастным ограничением собрали больше всего денег в прокате? Меняется ли картина в зависимости от года?

In [27]:
data['year'] = pd.to_datetime(data['year'], errors='coerce')
data['year'] = data['year'].dt.year
data = data.dropna(subset=['year'])
data['year'] = data['year'].astype(int)

In [28]:
print("Количество фильмов до фильтрации:", len(data))

filtered = data[(data['year'] >= 2015) & (data['year'] <= 2019)]

print("Количество фильмов после фильтрации:", len(filtered))

age_revenue = filtered.groupby('age_restriction')['box_office'].sum().sort_values(ascending=False)

display(age_revenue)

Количество фильмов до фильтрации: 7485
Количество фильмов после фильтрации: 3849

age_restriction
«16+» - для детей старше 16 лет           7.603473e+10
«12+» - для детей старше 12 лет           6.061945e+10
«6+» - для детей старше 6 лет             5.579861e+10
«18+» - запрещено для детей               4.075962e+10
«0+» - для любой зрительской аудитории    8.090774e+08
Name: box_office, dtype: float64

Как можно увидеть, чем выше возрастное ограничение, тем ниже прибыль. Это скорее всего связано с уменьшением числа потенциальных потребителей

<div class="alert alert-warning">
    <h2> Комментарий ревьюера v1 <a class="tocSkip"> </h2>
    
<b>Небольшие замечания и рекомендации💡:</b>  Вновь отмечаю, что не хватает визуализации

### Шаг 4. Исследуйте фильмы, которые получили государственную поддержку

На этом этапе нет конкретных инструкций и заданий — поищите интересные закономерности в данных. Посмотрите, сколько выделяют средств на поддержку кино. Проверьте, хорошо ли окупаются такие фильмы, какой у них рейтинг.

Сколько денег выделяется на поддержку кино?

In [29]:
data['total_support'] = data['refundable_support'].fillna(0) + data['nonrefundable_support'].fillna(0)
total_support_sum = data['total_support'].sum()
print(f"Общая сумма поддержки кино: {total_support_sum} рублей")

Общая сумма поддержки кино: 20200688312.0 рублей

Средний рейтинг фильмов с поддержкой

In [30]:
data['ratings'] = pd.to_numeric(data['ratings'], errors='coerce')
avg_rating_supported = data[data['total_support'] > 0]['ratings'].mean()
avg_rating_no_support = data[data['total_support'] == 0]['ratings'].mean()

print(f"Средний рейтинг фильмов с поддержкой: {avg_rating_supported:.2f}")
print(f"Средний рейтинг фильмов без поддержки: {avg_rating_no_support:.2f}")

Средний рейтинг фильмов с поддержкой: 5.97
Средний рейтинг фильмов без поддержки: 6.48

Насколько хорошо окупаются поддерживаемые фильмы?

In [31]:
data['total_support'] = data['total_support'].replace(0, pd.NA)
data['profitability'] = data['box_office'] / data['total_support']
profitability_stats = data[['total_support', 'box_office', 'profitability']].dropna().describe()
display(profitability_stats)

         box_office
count  3.180000e+02
mean   1.324324e+08
std    3.348379e+08
min    1.550000e+03
25%    1.236676e+06
50%    1.572007e+07
75%    1.063730e+08
max    3.073569e+09

Средний кассовый сбор - 132 миллиона рублей, а медианный сбор - 15 млн

<div class="alert alert-warning">
    <h2> Комментарий ревьюера v1 <a class="tocSkip"> </h2>
    
<b>Небольшие замечания и рекомендации💡:</b>  Каачествення работа! Добавил бы детальное исследовние режиссеров, продюсеров, студий, а также визуаалзиации

### Шаг 5. Напишите общий вывод

Из анализа данных можно сделать несколько выводов. В последние годы данные о прокатах заполняется более активно нежели раньше. Сумма с прокатов так же увеличилась, но тяжело сказать что повлияло на это больше, увеличение интереса к фильмам или ослабления рубля. Возрастное ограничение определенно влияет на сумму проката, чем меньше минимальный возраст, тем больше людей могут посмотреть фильм, что тем самым приводит к большим прокатам.

Суммарно за последнее время на поддержку фильмом было потрачено 20 миллиардов рублей. Средний рейтинг фильмов без поддержки немного лучше чем у фильмом с поддержкой, возможно из-за более сильной мотивации и финансовой ответственности режиссера. Основная масса фильмом имеет небольшие сбор, а средний кассовый сбор сильно повышен из-за блокабастеров

<div class="alert alert-success">
<h2> Комментарий ревьюера v1 <a class="tocSkip"> </h2>

<b>Все супер!👍:</b> Итоговый вывод полностью отражает проделанную работу

<div style="border:solid Chocolate 2px; padding: 40px">

**Общий вывод по проекту ревьювера v1**:

Антон, спасибо за  проект! Ты приложил много усилий, чтобы довести его до конца, проделана огромная работа, и это видно невооруженным глазом, ты большой молодец!

**Отмечу положительные моменты**:

1. Все разложено по полочкам, всегда понятен ход твоих мыслей, приятно смотреть

2. Отличные визуализации

3. На разных шагах проекта ты предлагал очень интересные решения и методы для их реализации. Хорошая работа!

**На что стоит обратить внимание**:

1. Не использован метод head сразу после чтения датафрейма

2. Не проверена правильность объединения данных

3. Не посчитана доля фильмов с известными данными о прокате

**Удачи и жду твой проект на повторное ревью!**